version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holders
      MYSQL_USER: holders
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
